
# Jekyll configuration for BMW Concierge
title: BMW Concierge
description: A tailored unofficial companion experience to the MyBMW Application
baseurl: "/BMW-Concierge"
url: "https://chatala1.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude files from build
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/

# GitHub OAuth settings (configured for BMW Concierge)
github:
  client_id: "Ov23liNCmhgdtQrBTgfI" # GitHub OAuth App client ID
  redirect_uri: "https://chatala1.github.io/BMW-Concierge/login.html"

# Smartcar API settings (configured with specified credentials)
smartcar:
  client_id: "37a67e2d-bc6d-42be-9b82-6ee450489d2b" # Smartcar client ID from issue requirements
  redirect_uri: "https://chatala1.github.io/BMW-Concierge/smartcar/callback"
  scope: "control_charge control_climate control_navigation control_pin control_security control_trunk read_alerts read_battery read_charge read_charge_events read_charge_locations read_charge_records read_climate read_compass read_diagnostics read_engine_oil read_extended_vehicle_info read_fuel read_location read_odometer read_security read_service_history read_speedometer read_thermometer read_tires read_user_profile read_vehicle_info read_vin"
  mode: "simulated" # Use simulated mode as specified in issue
  # Add the allowlist URL mentioned in the issue
  dashboard_config_url: "https://smartcar.com/docs/connect/dashboard-config"

# Site settings
author: BMW Concierge Team
email: ""

# Social links
github_username: chatala1

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
