
# Jekyll configuration for BMW Concierge
title: BMW Concierge
description: A tailored unofficial companion experience to the MyBMW Application
baseurl: "/BMW-Concierge"
url: "https://chatala1.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude files from build
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/

# GitHub OAuth settings (configured for BMW Concierge)
github:
  client_id: "Ov23liNCmhgdtQrBTgfI" # GitHub OAuth App client ID
  redirect_uri: "https://chatala1.github.io/BMW-Concierge/login.html"

# Smartcar API settings (to be configured with actual credentials)
smartcar:
  client_id: "" # To be configured with actual Smartcar client ID
  redirect_uri: "https://chatala1.github.io/BMW-Concierge/smartcar/callback"
  scope: "read_vehicle_info read_location read_odometer control_security control_climate"
  # Add the allowlist URL mentioned in the issue
  dashboard_config_url: "https://smartcar.com/docs/connect/dashboard-config"

# Site settings
author: BMW Concierge Team
email: ""

# Social links
github_username: chatala1

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
