
# Jekyll configuration for BMW Concierge
title: BMW Concierge
description: A tailored unofficial companion experience to the MyBMW Application.
baseurl: ""
url: "https://chatala1.github.io/BMW-Concierge"

# Theme
theme: minima

# Build settings
markdown: kramdown
highlighter: rouge
incremental: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site/

# GitHub Pages settings
repository: chatala1/BMW-Concierge
github:
repository_url: https://github.com/chatala1/BMW-Concierge

remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: dark

# Jekyll configuration for BMW Concierge
title: BMW Concierge
description: A tailored unofficial companion experience to the MyBMW Application
baseurl: "/BMW-Concierge"
url: "https://chatala1.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude files from build
exclude:
  - README.md
  - LICENSE
  - .gitignore
  - .github/

# GitHub OAuth settings (these would be set as environment variables)
github:
  client_id: "" # To be configured in GitHub Pages settings

# Site settings
author: BMW Concierge Team
email: ""

# Social links
github_username: chatala1

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
main

